-- Migration: unify-pulse-currency
-- Generated by developer assistant to record Prisma schema-level renames from "credits"/"balance" fields
-- NOTE: This migration intentionally does not alter existing database columns.
-- Rationale: Prisma model fields were renamed to use `pulse*` names, but @map() was added
-- to preserve existing column names (credits, credits_spent, credits_added, amount, balance_before, balance_after).
-- This keeps the DB schema stable while updating application-level names.
-- Apply this migration as a placeholder to advance the Prisma migration history.

/* No-op SQL: Recording rename at Prisma schema level. */

-- If you prefer actual column renames in the database, replace the section below with SQL
-- statements like: ALTER TABLE `users` CHANGE `credits` `pulse_balance` INT UNSIGNED NOT NULL DEFAULT 0;
-- But DO NOT run destructive column renames on production without backup and coordination.

-- End of migration
