module.exports = {
  apps: [
    {
      name: 'web-truyen-audio-web',
      script: '../../node_modules/next/dist/bin/next',
      args: 'start -p 3058',
      cwd: './apps/web',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3058,
        DISPLAY: ':99',
      },
      error_file: './logs/web-err.log',
      out_file: './logs/web-out.log',
      log_file: './logs/web-combined.log',
      time: true,
    },
    {
      name: 'web-truyen-audio-admin',
      script: '../../node_modules/next/dist/bin/next',
      args: 'start -p 3059',
      cwd: './apps/admin',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3059,
        DISPLAY: ':99',
      },
      error_file: './logs/admin-err.log',
      out_file: './logs/admin-out.log',
      log_file: './logs/admin-combined.log',
      time: true,
    },
  ],
};
