approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  "@angular-devkit/schematics-cli@*":
    dependencies:
      "@types/node": "*"
  "@nestjs/cli@*":
    dependencies:
      "@types/node": "*"
