nodeLinker: node-modules

enableGlobalCache: true
enableScripts: true

packageExtensions:
  "@nestjs/cli@*":
    dependencies:
      "@types/node": "*"
  "@angular-devkit/schematics-cli@*":
    dependencies:
      "@types/node": "*"
