module.exports = {
    apps: [
        {
            name: "auth-be",
            script: "./dist/main.js",
            instances: 1,
            exec_mode: "cluster",
            autorestart: true,
            watch: false,
            max_memory_restart: "1G",
            env: {
                PORT: 8035,
                NODE_ENV: "production",
                APP_ROLE: "api",
            },
            error_file: "./logs/api-err.log",
            out_file: "./logs/api-out.log",
            log_file: "./logs/api-combined.log",
            time: true,
        },
        {
            name: "auth-be-worker",
            script: "./dist/main.js",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                APP_ROLE: "worker",
            },
            error_file: "./logs/worker-err.log",
            out_file: "./logs/worker-out.log",
            log_file: "./logs/worker-combined.log",
            time: true,
        },
        {
            name: "auth-be-scheduler",
            script: "./dist/main.js",
            instances: 1,
            exec_mode: "fork",
            autorestart: true,
            watch: false,
            max_memory_restart: "512M",
            env: {
                NODE_ENV: "production",
                APP_ROLE: "scheduler",
            },
            error_file: "./logs/scheduler-err.log",
            out_file: "./logs/scheduler-out.log",
            log_file: "./logs/scheduler-combined.log",
            time: true,
        },
    ],
};
